# Generated by Django 4.2.7 on 2025-07-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Order Created'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('confirmed', 'Order Confirmed'), ('confirmation_sent', 'Confirmation Sent'), ('shipped', 'Order Shipped'), ('delivered', 'Order Delivered'), ('cancelled', 'Order Cancelled'), ('refunded', 'Order Refunded'), ('note_added', 'Note Added')], max_length=20),
        ),
    ]
